DROP DATABASE IF EXISTS recipes;
CREATE DATABASE recipes; 
USE recipes;

CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
userName VARCHAR(15) NOT NULL,
email VARCHAR(80) NOT NULL,
password VARCHAR(80) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);